### PR TITLE
harden against locale issues (upstream #315), fix exception typo

### PR DESCRIPTION
**Pull request by asiekierka**

### CODE REVIEW

**Comment by Mumfrey** [comment]
A fix for the issue is already included in 0.8 and no further builds of 0.7 will be released so I'm closing this. Thanks for the contribution though it's appreciated.

**Comment by RDIL** [comment]
Any updates on 0.8?

**Comment by Mumfrey** [comment]
It's complete except for final tweaks to the annotation processor.

**Comment by RDIL** [comment]
Can’t wait 😃

**Pull request closed without merging**
