### PR TITLE
Added MDDocs Plugin + generated MD Docs

### PR DESCRIPTION
**Pull request by VRCube**
Task to generate MDDocs is `genDoc`, documents are generated in `docs` folder

### CODE REVIEW

**Comment by VRCube** [comment]
This is fix of #240

**Comment by simon816** [comment]
This seems pointless. If someone wanted the javadocs they can just download them here https://repo.spongepowered.org/maven/org/spongepowered/mixin/
And are available online here: http://jenkins.liteloader.com/job/Mixin/javadoc/

I don't see what 21,000 lines of bloat adds to this repository.
Most of the classes are inner-workings of mixin, having documentation on them doesn't add much.

Also, since you're proposing to bake this into the repository, it'll get stale quickly. Automated documentation should be part of the build process, like javadocs.

Maybe you could explain why this is wanted?

**Comment by mikroskeem** [comment]
Nevertheless it's a 21k lines of bloat.

If you really want documentation in Markdown format, you can host one by yourself on GitHub. For example make Jenkins to poll Mixin repository and Gradle to generate & publish documentation.

**Comment by VRCube** [comment]
Well, In case other people who wants to view the doc 🤷‍♂️

**Comment by Zidane** [comment]
I'm going to save @Mumfrey the time and energy and close this now. As others stated above, host markdown ones yourself please.

**Pull request closed without merging**
