### PR TITLE
Fix a simple typo in the README.md

### PR DESCRIPTION
**Pull request by MCPfannkuchenYT**
extrememly -> extremely

### CODE REVIEW

**Comment by Zidane** [comment]
We don't take formatting PRs.

**Comment by MCPfannkuchenYT** [comment]
Still, please fix it

**Comment by Earthcomputer** [comment]
Literally unusable

**Comment by Aizistral** [comment]
> Literally unusable

Well, I mean, be strange if it was like "We don't formatting PRs, but not gonna fix mistakes ourselves either"

**Pull request closed without merging**
