### PR TITLE
Fix gradle building and classloader casting on Java 9+

### PR DESCRIPTION
**Pull request by xIGBClutchIx**

### CODE REVIEW

**Comment by Mumfrey** [comment]
*Clutch*! Holy hell that's a name I haven't seen in a while!

With respect to this PR, are you saying that this makes Mixin work properly under Java 9 under LaunchWrapper? If so, how? Since LW doesn't support Java 9 itself and is fully deprecated in favour of ModLauncher going forward there shouldn't really be any situation where projects that want to support Java 9 and beyond are still using it.

**Comment by xIGBClutchIx** [comment]
Haha yeah long time no see Mumfrey!

Yeah I personally got Mixin working with a [unofficial LegacyLauncher](https://github.com/LightWayUp/LegacyLauncher) and that little fix in Mixin. I have not fully wrapped my head around ModLauncher yet with it being somewhat new so I decided to continue on my work with working with LegacyLauncher for the time being. Completely understand the want to deprecated it.

**Comment by Mumfrey** [comment]
Having thought about this for a while. I've decided I'm going to include it on the basis that:

* It doesn't hurt anything
* This doesn't come with any attached implications of Mixin working properly with Java 9, only that it won't explode.

However, I feel it's important to point out the following:

* The whole point of mixin's contact with the "outside world" being encased in the service is so that additional services can be easily plugged-in in order to support other environments.
* "Unofficial LegacyLauncher" opens up a can of worms and really the entire thing should not only move artefact coordinates but should also use an entirely different namespace. Because it's the same namespace, the official LL service has no way to determine the difference between the real LL and the unofficial fork
* A cleaner way to do this would be to wrap this new logic in a new mixin service and bundle that. Potentially it can override if it's just placed correctly in the classpath.

As a corollary to this, I feel compelled to move the expression of compatibility into the service so that I can raise a warning when the desired compatibility level is outside the supported range of the service in use. I **do not** want to incur a support burden when mixin is used outside of known good environments. I consider using a service designed for one environment to operate in another to fall under this category. This means any concerns with the warning can be immediately addressed by doing things "properly" and providing a service which properly represents the target environment.

Please can you squash this branch. I will add the version-in-service stuff on top before I merge this.

If you have any comments on the above, I'm happy to hear them.

**Comment by xIGBClutchIx** [comment]
Nope I completely agree with has been said. Personally I am going to make the switch over to modlauncher soon because I love how mixin runs as a service.
I also pushed #366 After I broke all the things. lol

**Comment by Mumfrey** [comment]
I think you'll find it a pretty nice environment to work in. So many more things are properly defined in modlauncher versus the kind of wild west, "figure it out for yourself" lands of LegacyLauncher and it's just super refreshing to work with. I thoroughly recommend it.

Also cpw is actively working to make it do all the things it still doesn't do, so it's not like anything it's missing is going to be a problem either.

**Pull request closed without merging**
