### PR TITLE
Fix `Args` subclass generation on modern ModLauncher.

### PR DESCRIPTION
**Pull request by LlamaLad7**
Title says it all. `ModifyArgs` is usable now.

### CODE REVIEW

**Comment by Fourmisain** [comment]
Thank you so much!
I just ran into a crash issue with the Forge version of Chat Heads (and only the Forge version), erroring out with
> java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1

and had no idea what was going on - thought it was an architectury build issue or something.

Adding a (randomly named) dummy class to the package did fix this issue.
This just saved me a lot of headache!

**Comment by LlamaLad7** [comment]
You can't do it yourself or you'll get an overlapping packages crash when someone else does. Consider a <https://github.com/LlamaLad7/MixinExtras/wiki/WrapOperation>

**Comment by Fourmisain** [comment]
> You can't do it yourself or you'll get an overlapping packages crash when someone else does

But only if the class names are identical, right? I'm fairly certain [my naming is unique](https://github.com/dzwdz/chat_heads/blob/main/forge/src/main/java/org/spongepowered/asm/synthetic/args/ForgeYouStupidBaka.java).
I'll take a look at the WrapOperation though, thanks again!

**Comment by LexManos** [comment]
The point is that Mixin itself has to put something in that package. The Java module system is what dictates that only one thing can claim a package. Naming your class something else doesn't work because you're still attempting to claim that package. So you will run into issues if anyone else does it. Mumfrey just needs to accept this or something similiar.

**Comment by Fourmisain** [comment]
Well, dang!
I guess I rally have to fix the "fix", back to the drawing board (and that WrapOperation).

**Pull request closed without merging**
