### PR TITLE
Fix broken class references in PluginHandle

### PR DESCRIPTION
**Pull request by RDIL**
Couldn't build the project because of these

### CODE REVIEW

**Comment by Mumfrey** [comment]
What? No!

The entire point of the shim is backward compatibility, why would I want to "fix" this?!!?!

**Comment by RDIL** [comment]
This was causing errors and I couldn't build the project

**Comment by Mumfrey** [comment]
Oh I see the problem, gitignore has caused part of the codebase to not be tracked by git.

**Comment by Mumfrey** [comment]
8965b0a3f20f11f6fa42188a01f422df7e868ead

**Pull request closed without merging**
